export const LOGIN = 'LOGIN';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const UPDATE_LOGIN_FIELDS = 'UPDATE_LOGIN_FIELDS';

export const LOAD_COMPANIES_FROM_SERVER = 'LOAD_COMPANIES_FROM_SERVER';

export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const UPDATE_CURRENT_COMPANY_FIELDS = 'UPDATE_CURRENT_COMPANY_FIELDS';
export const SAVE_CURRENT_COMPANY = 'SAVE_CURRENT_COMPANY';

export const SET_CURRENT_CLINIC = 'SET_CURRENT_CLINIC';
export const UPDATE_CURRENT_CLINIC_FIELDS = 'UPDATE_CURRENT_CLINIC_FIELDS';
export const SAVE_CURRENT_CLINIC = 'SAVE_CURRENT_CLINIC';

export const SET_CURRENT_DOCTOR = 'SET_CURRENT_DOCTOR';
export const UPDATE_CURRENT_DOCTOR_FIELDS = 'UPDATE_CURRENT_DOCTOR_FIELDS';
export const SAVE_CURRENT_DOCTOR = 'SAVE_CURRENT_DOCTOR';
export const UPLOAD_PHOTO_DOCTOR = 'UPLOAD_PHOTO_DOCTOR';
